# Copyright © 2023 Pittsburgh Supercomputing Center.
# All Rights Reserved.

Bootstrap: docker
From: alpine:latest

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/icaoberg/singularity-pandiff
    COPYRIGHT Copyright © 2023 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 5.0.0

%post
    apk add --update nodejs npm
    npm install --global pandiff
